package com.yupao.app.ui.main

import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import com.cc.ktx_ext_base.base.BaseViewModel
import com.yupao.app.model.bean.MainList
import kotlin.random.Random

class MainViewModel : BaseViewModel() {

    var test  = MutableLiveData<String>()
    var datas = arrayListOf<MainList>()

    fun setdata(){
        datas.clear()
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))
        datas.add(MainList("2"+(1..500).random()))



    }

}
